version: '3.3'

services:
  nestjs:
    build: .
    tty: true
    ports:
      - '3030:3000'
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
    command: 'yarn start:dev'
    networks:
      - shared-network
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'admin'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'pass'
    ports:
      - '3316:3306'
    volumes:
      - cinema_app_db:/var/lib/mysql
    networks:
      - shared-network

networks:
  shared-network:
    external: true

volumes:
  cinema_app_db:
