### sayHello

Get http://localhost:3030/
Content-Type: application/json

### signUp

POST http://localhost:3030/auth/signup
Content-Type: application/json

{
  "email": "aee11s@eees.coaam",
  "password": "fuck",
  "username": "osushi",
  "icon": "sss",
  "iconColor": "red",
  "admin": true
}

### login

POST http://localhost:3030/auth/login
Content-Type: application/json

{
  "email": "eee@eee.com",
  "password": "fuck"
}

### logOut

POST http://localhost:3030/auth/logout
Content-Type: application/json
